language: go
sudo: false

git:
  depth: false

#Each one of these scripts is run in parallel.
script:
  - go build src/solutions/p1Multiplesof3And5/main.go && ./bin/main.exe
  - go build src/solutions/p2EvenFibonacciNumbers/main.go && ./bin/main.exe
  - go build src/solutions/p3LargestPrimeFactor/main.go && ./bin/main.exe
  - go build src/solutions/p4LargestPalindomeProduct/main.go && ./bin/main.exe