language: go

git:
  depth: false

# We need to set this so that we can install golangci-lint in vendor dir.
env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'
  global:
    # Workaround for when travis_setup_go can't identify the Go version.
    - TRAVIS_GO_VERSION="$(cat .go-version)"
  

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

#Each one of these scripts is run in parallel.
script:
  - golangci-lint run
  - go build src/solutions/p1multiplesof3And5/main.go
  - go build src/solutions/p2EvenFibonacciNumbers/main.go
  - go build src/solutions/p3LargestPrimeFactor/main.go
  - go build src/solutions/p4LargestPalindromeProduct/main.go